server:
  port: 8091
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_all?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

mybatis:
  mapper-locations:
  # - 表示数组
  - classpath:mapper/*.xml
  - classpath*:com/**/mapper/*.xml