server:
  port: 8091
  
spring:
  datasource:
    url: jdbc:mysql://192.168.220.138:3306/mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

mybatis:
  mapper-locations:
  # - 表示数组
  - classpath:mapper/*.xml
  - classpath*:com/**/mapper/*.xml