server:
  port: 8091
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_all?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

mybatis:
  mapper-locations:
  # - 表示数组
  - classpath:mapper/*.xml
  - classpath*:com/**/mapper/*.xml
  
# OSS 相关配置
aliyun:
 oss:  
   # oss 对外服务的访问域名
   endpoint: oss-cn-shenzhen.aliyuncs.com
   # 访问身份验证中用到的用户标识
   accessKeyId: test
   # 用户用于加密签名字符串和 oss 用来验证签名字符串的密钥
   accessKeySecret: test
   # oss 存储空间
   bucketName: macro-oss
   policy:
     # 签名有效期(s) 
     expire: 300
     # 上传文件大小(m)
   maxSize: 10
     # 文件上传成功后的回调地址
   callback: http://localhost:8091/aliyun/oss/callback
   dir:
       # 上传文件夹路径前缀
       prefix: mall/images/